import os
import time
import contextvars
import functools
import google.generativeai as genai
from google.generativeai.types import content_types

from mcp_server.tools.flight_time import calculate_flight_time
from mcp_server.tools.roi_calc import calculate_roi
from mcp_server.tools.compliance_checker import check_compliance
from mcp_server.tools.drone_selector import select_drone
from mcp_server.rag_bridge import query_pinecone, format_citations

# Ensure Gemini is configured
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

def retrieve_knowledge_base(query: str, top_k: int = 15) -> dict:
    """
    Searches the Pinecone Drone Intelligence vector database for relevant documentation.
    Use this tool whenever the user asks a general knowledge question about drones, rules, markets, or operations.
    Returns paragraphs of context to help form an answer.
    """
    chunks = query_pinecone(query, top_k=top_k)
    return {
        "context": [c["text"] for c in chunks],
        "citations": format_citations(chunks)
    }

async def execute_agent(message: str, conversation_history: list = None) -> dict:
    """
    The main agent loop capable of executing functions returning the response.
    """
    start_time = time.time()
    local_citations = []
    
    local_mcp_tools = [
        calculate_flight_time,
        calculate_roi,
        check_compliance,
        select_drone,
        retrieve_knowledge_base
    ]
    
    system_instruction = (
        "You are the central Drone Intelligence routing agent. Your job is to answer user queries accurately. "
        "Answer in under 100 words clearly and concisely. "
        "CRITICAL: For EVERY user query about drones, institutes, business, or Indian DGCA regulations, YOU MUST call the `retrieve_knowledge_base` tool to search Pinecone before answering! "
        "Even if you feel you already know the answer from previous conversation history, you MUST still call the tools to theoretically force the system to generate the citation brackets! Do NOT answer factual queries blindly from chat history. "
        "When synthesizing the retrieved chunks, you MUST cite the exact citation labels generated by the tool directly inside your text using brackets, e.g. [training_institutes.csv (row 12)]. "
        "DO NOT use your internal general knowledge. ALWAYS use the `retrieve_knowledge_base` tool first, then synthesize the returned chunks into your final answer. "
        "DO NOT use tools for casual greetings like 'hi' or 'hello'. "
        "If the tools do not contain the answer, state that you do not know based on the provided intelligence. "
        "When parsing user input into tool arguments, rigorously ensure the types and formats match exactly what the tool requires. "
        "For example, convert string numbers ('30kg') to raw float values (30.0). "
        "If multiple tools are needed, you may execute them iteratively. "
        "Once you have gathered the data from the tools, synthesize it into a clean, markdown-formatted response."
    )

    local_agent_model = genai.GenerativeModel(
        model_name="models/gemini-3-flash-preview",
        tools=local_mcp_tools,
        system_instruction=system_instruction
    )

    chat = local_agent_model.start_chat(
        enable_automatic_function_calling=True,
        history=conversation_history
    )
    
    response = await chat.send_message_async(message)
    
    raw_citations = []
    tool_used = "llm"
    
    # Extract tools and citations directly from the SDK's history AST structs
    for msg in chat.history:
        if getattr(msg, "parts", None):
            for p in msg.parts:
                # Track which tool was called
                if getattr(p, "function_call", None):
                    tool_used = p.function_call.name
                
                # Extract citation strings from the returned tool payloads
                if getattr(p, "function_response", None):
                    resp = p.function_response.response
                    resp_dict = {}
                    if hasattr(type(resp), 'to_dict'):
                        resp_dict = type(resp).to_dict(resp)
                    elif hasattr(resp, 'items'):
                        resp_dict = dict(resp)
                    
                    if "citations" in resp_dict:
                        for c in resp_dict["citations"]:
                            raw_citations.append(str(c))
                            
    # Filter the 15 raw citations down to only the ones actually quoted by Gemini in the text!
    citations = []
    answer_text = response.text
    for c in set(raw_citations):
        # Gemini often drops the ', record_id:' part to be theoretically concise. 
        # Match only the fundamental title/row text mathematically.
        base_c = c.split(", record_id:")[0].strip()
        if base_c in answer_text:
            citations.append(c)
            
    # Scrub the raw physical brackets from the final answer text 
    # to avoid polluting the chat UI (since we render citation cards anyway).
    import re
    # Safely target any document brackets ending in .csv/.txt/.pdf bounds so we don't accidentally erase code arrays
    answer_text = re.sub(r'\s*\[.*?(?:\.csv|\.txt|\.pdf).*?\]\s*', ' ', answer_text)
        
    # Collapse any dangling spaces left directly before punctuation marks like " . " -> "."
    answer_text = re.sub(r'\s+([.,!?;:])', r'\1', answer_text).strip()

    processing_time_ms = round((time.time() - start_time) * 1000, 2)

    return {
        "answer": answer_text,
        "citations": citations,
        "tool_used": tool_used,
        "processing_time_ms": processing_time_ms
    }
